In [1]:
import pandas as pd
import re
import matplotlib.pyplot as plt
from cycler import cycler
%matplotlib inline
import seaborn as sns

In [2]:
plt.rcdefaults()
plt.rcParams.update({
    'pdf.fonttype': 42,
    'ps.fonttype': 42,
    'font.family': 'sans-serif',
    'font.sans-serif' : 'Tahoma',
    'axes.facecolor' : '#ffffff',
    'axes.axisbelow':True, 
    'axes.grid' : True,
    'grid.color' : '#bec0c2',
    'grid.linestyle' : 'dotted',
    'axes.spines.left'   : False,   
    'axes.spines.bottom' : False,
    'axes.spines.top'    : False,
    'axes.spines.right' : False,
    'axes.prop_cycle': cycler('color', ['chartreuse','mediumseagreen','mediumaquamarine','mediumturquoise','cadetblue','skyblue','teal',
                                        'mediumspringgreen','seagreen']),
    'xtick.bottom'  : False,
    'ytick.left': False,
    'figure.titlesize' : 'large', 
    'figure.titleweight' : 'bold',
    'figure.facecolor' : '#ffffff',
    'text.color' : '#595959',
    'axes.labelcolor' : '#595959',
    'xtick.color' : '#595959',
    'ytick.color' : '#595959',
    'legend.loc' : 'best',
    'legend.fancybox'    : True,
    'legend.frameon'     : True,
    'legend.edgecolor'     : '0.9',
    'legend.markerscale'   : '0.5',
    'lines.marker'      : None,
    'lines.markersize'  : 3,           
})

In [3]:
playas=pd.read_csv('Monitoreo de Playas 2018')
playas.tail()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
843,2018-10-02,RW-39,Mar Chiquita,18.472917,-66.485656,Route: 6: Arecibo – Vega Alta,Routine,<10,28.40,8.33,NaN
844,2018-10-02,RW-23,Balneario de Puerto Nuevo,18.491367,-66.399044,Route: 6: Arecibo – Vega Alta,Routine,10,28.40,8.27,NaN
845,2018-10-02,RW-17,Balneario Cerro Gordo or Javier Calderón Nieves,18.481250,-66.340656,Route: 6: Arecibo – Vega Alta,Routine,10,29.30,8.28,NaN
846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
playas2=pd.read_csv("Monitoreo 2016 y 2017.csv")
playas2.tail()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
894,2017-08-28,RW-16,Balneario Crash Boat,18.457667,-67.163778,Route 5: Añasco - Aguadilla,Routine,238,30.1,8.14/8.15,Preliminar
895,2017-08-29,RW-38,Muelle de Arecibo,18.479258,-66.700467,Route: 6: Arecibo – Vega Alta,Routine,272,29,8.13,Preliminar
896,2017-08-29,RW-39,Mar Chiquita,18.472917,-66.485656,Route: 6: Arecibo – Vega Alta,Routine,10,29,8.21,Preliminar
897,2017-08-29,RW-23,Balneario de Puerto Nuevo,18.491367,-66.399044,Route: 6: Arecibo – Vega Alta,Routine,20,29.3,8.19,Preliminar
898,2017-08-29,RW-17,Balneario Cerro Gordo or Javier Calderón Nieves,18.481250,-66.340656,Route: 6: Arecibo – Vega Alta,Routine,10,29.5,8.21/8.20,Preliminar

In [5]:
playas3=pd.read_csv("Monitoreo 2015 y 2016.csv")
playas3.tail()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
1425,2016-09-27,RW-4,Balneario Punta Santiago,18.1584139,-65.7551861,Route 2: Arroyo - Luquillo,Routine,10,30.60,8.15,NaN
1426,2016-09-27,RW-31,Tropical Beach,18.1869278,-65.7259667,Route 2: Arroyo - Luquillo,Routine,116,31.20,8.15/8.15,NaN
1427,2016-09-27,RW-2,Balneario Seven Seas,18.3692667,-65.6360722,Route 2: Arroyo - Luquillo,Routine,10,31.40,8.11,NaN
1428,2016-09-27,RW-32,Playa Azul,18.3818667,-65.7184583,Route 2: Arroyo - Luquillo,Routine,10,29.70,8.18,NaN
1429,2016-09-27,RW-1A,Balneario La Monserrate,18.3855917,-65.7294722,Route 2: Arroyo - Luquillo,Routine,10,29.70,8.16,NaN

In [6]:
playas3.head()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
0,2015-01-07,RW-18,Balneario Manuel “Nolo” Morales or Sardinera,Route 1: Dorado - Loíza,Routine,240,24,23.90,8.16/8.15,The information provided is preliminary .,NaN
1,2015-01-07,RW-19,Balneario Punta Salinas,Route 1: Dorado - Loíza,Routine,8,1,25.00,8.13,The information provided is preliminary .,NaN
2,2015-01-07,RW-20A,Balneario El Escambrón,Route 1: Dorado - Loíza,Routine,1,1,24.60,8.08,The information provided is preliminary .,NaN
3,2015-01-07,RW-21C,Balneario de Carolina,Route 1: Dorado - Loíza,Routine,1,1,25.30,8.12,The information provided is preliminary .,NaN
4,2015-01-07,RW-25A,Playa Sixto Escobar,Route 1: Dorado - Loíza,Routine,240,24,24.50,8.03,The information provided is preliminary .,NaN

In [7]:
playasdePuertoRico=pd.concat([playas2,playas],sort=False, ignore_index=True)
playasdePuertoRico.tail()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
1742,2018-10-02,RW-39,Mar Chiquita,18.472917,-66.485656,Route: 6: Arecibo – Vega Alta,Routine,<10,28.40,8.33,NaN
1743,2018-10-02,RW-23,Balneario de Puerto Nuevo,18.491367,-66.399044,Route: 6: Arecibo – Vega Alta,Routine,10,28.40,8.27,NaN
1744,2018-10-02,RW-17,Balneario Cerro Gordo or Javier Calderón Nieves,18.481250,-66.340656,Route: 6: Arecibo – Vega Alta,Routine,10,29.30,8.28,NaN
1745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
Total_playasdePuertoRico=pd.concat([playas3,playasdePuertoRico],sort=False, ignore_index=True)
Total_playasdePuertoRico.head()

,Date,Beach ID,Beach Name,Latitude,Longitude,Sampling Route,Sampling Type,Enterococcus (colonies/100 mL),Temperature (°C),pH,Observations
0,2015-01-07,RW-18,Balneario Manuel “Nolo” Morales or Sardinera,Route 1: Dorado - Loíza,Routine,240,24,23.90,8.16/8.15,The information provided is preliminary .,NaN
1,2015-01-07,RW-19,Balneario Punta Salinas,Route 1: Dorado - Loíza,Routine,8,1,25.00,8.13,The information provided is preliminary .,NaN
2,2015-01-07,RW-20A,Balneario El Escambrón,Route 1: Dorado - Loíza,Routine,1,1,24.60,8.08,The information provided is preliminary .,NaN
3,2015-01-07,RW-21C,Balneario de Carolina,Route 1: Dorado - Loíza,Routine,1,1,25.30,8.12,The information provided is preliminary .,NaN
4,2015-01-07,RW-25A,Playa Sixto Escobar,Route 1: Dorado - Loíza,Routine,240,24,24.50,8.03,The information provided is preliminary .,NaN

In [ ]:
Total_playasdePuertoRico['Beach Name'].value_counts()

In [ ]:
import re

In [ ]:
Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)']=Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)'].fillna(0)

In [ ]:
Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)']=Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)'].str.extract(r'<?(.*)')

In [ ]:
Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)'].describe()

In [ ]:
Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)']=pd.to_numeric(Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)'], errors='coerce')

In [ ]:
Total_playasdePuertoRico= Total_playasdePuertoRico[Total_playasdePuertoRico['Enterococcus\r\n (colonies/100 mL)'] > 70]
Total_playasdePuertoRico.shape

In [ ]:
Total_playasdePuertoRico['Date']=pd.to_datetime(Total_playasdePuertoRico['Date'],format='%Y-%m-%d')

In [ ]:
Total_playasdePuertoRico['Year'] = Total_playasdePuertoRico['Date'].dt.year
Total_playasdePuertoRico['Month'] = Total_playasdePuertoRico['Date'].dt.month

In [ ]:
#Contaminación en comparación con otras playas
final = Total_playasdePuertoRico.pivot_table(index="Beach Name",columns="Year",values="Enterococcus\r\n (colonies/100 mL)", aggfunc="mean").fillna(0)
plt.figure(figsize=(5, 8))
cmaps = 'ocean'
#gradient = np.linspace(0, 1, 256)
#gradient = np.vstack((gradient, gradient))
sns.heatmap(final, annot=None, cmap=cmaps)
#plt.tight_layout()
plt.savefig('Contaminación en comparación con otras playas.pdf', transparent=True)
plt.show()

In [ ]:
#Mergin two different data frames to seethe conditions of the most visited beaches
most_visited= Total_playasdePuertoRico[Total_playasdePuertoRico['Beach Name'].isin(['Playita del Condado','Balneario de Carolina',
                                                              'Balneario de Boquerón','Playa Buyé','Balneario El Escambrón',
                                                              'Balneario Seven Seas',
                                                              'Balneario La Monserrate',
                                                              'Ocean Park',
                                                              'Playa el Combate','Balneario Crash Boat'])] 
most_visited

In [ ]:
Oeste = Total_playasdePuertoRico[Total_playasdePuertoRico['Beach Name'].isin(['Playa Moja Casabe','Pico de Piedra','Balneario de Añasco or Balneario Tres Hermanos', 'Playa el Combate',
'Balneario de Rincón',
'Playa Buyé', 'Balneario de Boquerón', 
'Balneario Crash Boat', 'Balneario Crash Boat','Playita Rosada',
'Villa Lamela', 'Playa Santa', 'Caña Gorda',  ' Villa Lamela'])] 
Oeste

In [ ]:
Oeste.tail()

In [ ]:
Oeste.to_csv('Muestreo oeste', index=False)

In [ ]:
#Playas del oeste de Puerto Rico 
Oeste_sucio = Oeste[Oeste['Enterococcus\r\n (colonies/100 mL)'] > 70]
Oeste_sucio

In [ ]:
Oeste_sucio['Date']=pd.to_datetime(Oeste_sucio['Date'],format='%Y-%m-%d')

In [ ]:
Oeste_sucio['Year'] = Oeste_sucio['Date'].dt.year
Oeste_sucio['Month'] = Oeste_sucio['Date'].dt.month

In [ ]:
Oeste_sucio=Oeste_sucio.rename(columns={'Enterococcus\r\n (colonies/100 mL)':'Enterococcus_colonies'})

In [ ]:
colors= ['chartreuse']
data= Oeste_sucio.groupby('Year').Enterococcus_colonies.max(ascending=True)
ax = data.plot(kind='barh',x='Enterococcus_colonies',y='Year',colors=colors)
ax.set_title("Valor máximo de enterocos en un año", pad=30, fontsize=24)
plt.tight_layout()
plt.savefig('Valor máximo de enterocos en un año.pdf',transparent=True)
plt.show()

In [ ]:
df1= Oeste_sucio.sort_values(by='Enterococcus_colonies',ascending=False).head(20)
ax= df1.plot(kind='barh', x='Beach Name', y='Enterococcus_colonies', figsize=(10,5),legend=False,rot=0,color='mediumaquamarine')
ax.set_title("Máximos puntos fecales en el oeste desde abril 2015", pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
#plt.gcf().text(0.5, 0.91, "Bacteria samples exceeding Puerto Rico's Environmental Quality Board parameters", ha='center', fontsize=12)
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('Máximos puntos fecales en el oeste desde abril 2015.pdf',transparent=True)
plt.show()

In [ ]:
Oeste_sucio['Beach Name'].value_counts()

In [ ]:
df1= Oeste_sucio['Beach Name'].value_counts()
ax= df1.plot(kind='barh', x='Beach Name', y='Enterococcus_colonies', figsize=(10,5),legend=False,rot=0,color='mediumaquamarine')
ax.set_title("Cuántas veces ha aparecido la playa sucia", pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
#plt.gcf().text(0.5, 0.91, "Bacteria samples exceeding Puerto Rico's Environmental Quality Board parameters", ha='center', fontsize=12)
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('Cuántas veces ha aparecido la playa sucia.pdf',transparent=True)
plt.show()

In [ ]:
final = Oeste_sucio.pivot_table(index="Beach Name",columns="Year",values="Enterococcus_colonies", aggfunc="mean").fillna(0)
plt.figure(figsize=(5, 8))
cmaps = 'ocean'
ax.set_title("Niveles de contaminación desde abril 2015", pad=30, fontsize=24)
#gradient = np.linspace(0, 1, 256)
#gradient = np.vstack((gradient, gradient))
sns.heatmap(final, annot=None, cmap=cmaps)
#plt.tight_layout()

plt.savefig('Dirty_beaches_in-westside_Puerto_Rico.pdf', transparent=True)
plt.show()

In [ ]:
final = Oeste_sucio.pivot_table(index="Beach Name",columns="Month",values="Enterococcus_colonies", aggfunc="mean").fillna(0)
plt.figure(figsize=(5, 8))
cmaps = 'ocean'
ax.set_title("Niveles de contaminación desde abril 2015", pad=30, fontsize=24)
#gradient = np.linspace(0, 1, 256)
#gradient = np.vstack((gradient, gradient))
sns.heatmap(final, annot=None, cmap=cmaps)
#plt.tight_layout()

plt.savefig('Dirty_beaches_in-westside_Puerto_Rico_per_month.pdf', transparent=True)
plt.show()

In [ ]:
Oeste_2018= Oeste_sucio[Oeste_sucio['Year']==2018]
Oeste_2018['Beach Name'].value_counts()

In [ ]:
Oeste_2017= Oeste_sucio[Oeste_sucio['Year']==2017]
Oeste_2017['Beach Name'].value_counts()

In [ ]:
Oeste_2017= Oeste_sucio[Oeste_sucio['Year']==2016]
Oeste_2017['Beach Name'].value_counts()

In [ ]:
df=Oeste_2018.sort_values(by='Enterococcus_colonies',ascending=False).head(20)
ax=df.plot(kind='barh', x='Beach Name', y='Enterococcus_colonies')
ax.set_title('Contaminación actual', pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
ax.patches
for i,bar in enumerate(ax.patches):
    value= int(round(bar.get_width()))
    x_pos= bar.get_width() - 1
    y_pos=i
    ax.text(x_pos,y_pos,value,verticalalignment='center',ha='right',color='grey')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('Contaminación en el año 2018.pdf',transparent=True)
plt.show()

In [ ]:
df=Oeste_2018.sort_values(by='Enterococcus_colonies',ascending=False).head(20)
ax=df.plot(kind='barh', x='Beach Name', y='Month')
ax.set_title('Contaminación actual', pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
ax.patches
for i,bar in enumerate(ax.patches):
    value= int(round(bar.get_width()))
    x_pos= bar.get_width() - 1
    y_pos=i
    ax.text(x_pos,y_pos,value,verticalalignment='center',ha='right',color='black')
plt.gca().invert_yaxis()
plt.tight_layout()
#plt.savefig('Contaminación reciente por mes.pdf',transparent=True)
plt.show()

In [ ]:
final = Oeste_2018.pivot_table(index="Beach Name",columns="Month",values="Enterococcus_colonies", aggfunc="mean").fillna(0)
plt.figure(figsize=(5, 8))
cmaps = 'ocean'
ax.set_title("Niveles de contaminación desde abril 2015", pad=30, fontsize=24)
#gradient = np.linspace(0, 1, 256)
#gradient = np.vstack((gradient, gradient))
sns.heatmap(final, annot=None, cmap=cmaps)
#plt.tight_layout()

plt.savefig('Contaminación_pormes_enel_2018.pdf', transparent=True)
plt.show()

In [ ]:
Oeste_limpio = Oeste[Oeste['Enterococcus\r\n (colonies/100 mL)'] < 70] 
Oeste_limpio

In [ ]:
Oeste_limpio['Date']=pd.to_datetime(Oeste_limpio['Date'],format='%Y-%m-%d')

In [ ]:
Oeste_limpio['Year'] = Oeste_limpio['Date'].dt.year
Oeste_limpio['Month'] = Oeste_limpio['Date'].dt.month

In [ ]:
Oeste_limpio_2018= Oeste_limpio[Oeste_limpio['Year']==2018]
Oeste_limpio_2018

df2=Oeste_limpio_2018['Beach Name'].value_counts()
ax=df2.plot(kind='barh', x='Beach Name', y='Enterococcus_colonies')
ax.set_title('Cantidad de veces que han aparecido limpias', pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('Limpias.pdf',transparent=True)
plt.show()

In [ ]:
df5=Oeste_limpio_2018.sort_values(by='Enterococcus\r\n (colonies/100 mL)',ascending=False).head(20)
ax=df5.plot(kind='barh', x='Beach Name', y='Enterococcus\r\n (colonies/100 mL)')
ax.set_title('niveles en limpias', pad=30, fontsize=24)
ax.set_xlabel('100 mililitros de agua (colonias /100mL)')
ax.patches
for i,bar in enumerate(ax.patches):
    value= int(round(bar.get_width()))
    x_pos= bar.get_width() - 1
    y_pos=i
    ax.text(x_pos,y_pos,value,verticalalignment='center',ha='right',color='grey')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('Niveles más altos en las que han aparecido limpias.pdf',transparent=True)
plt.show()

In [ ]:
#Septiembre
playas=pd.read_csv('')
playas.tail()